"""Runway model manifest captured from the Runway web app.

The manifest is intentionally data-only so the database layer can seed and
sync model rows without importing the Runway service.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional


RUNWAY_MANIFEST_VERSION = "2026-05-30-web-capture-1"

ASPECT_RATIOS_WIDE = ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
ASPECT_RATIOS_IMAGE = ["21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"]
ASPECT_RATIOS_RUNWAY_IMAGE = ["16:9", "9:16", "1:1", "4:3", "3:4", "21:9"]
ASPECT_RATIOS_KLING = ["16:9", "9:16", "1:1"]
ASPECT_RATIOS_SEEDANCE = ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]


def _schema(
    *,
    aspect_ratios: Optional[List[str]] = None,
    resolutions: Optional[List[str]] = None,
    image_sizes: Optional[List[str]] = None,
    durations: Optional[List[int]] = None,
    prompt_max: Optional[int] = None,
    extra: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    schema: Dict[str, Any] = {}
    if aspect_ratios:
        schema["aspect_ratio"] = {"type": "string", "enum": aspect_ratios}
    if resolutions:
        schema["resolution"] = {"type": "string", "enum": resolutions}
    if image_sizes:
        schema["image_size"] = {"type": "string", "enum": image_sizes}
    if durations:
        schema["duration"] = {"type": "integer", "enum": durations}
    if prompt_max:
        schema["prompt"] = {"type": "string", "max_length": prompt_max}
    if extra:
        schema.update(extra)
    return schema


RUNWAY_MODEL_MANIFEST: List[Dict[str, Any]] = [
    {
        "public_model_id": "runway-nano-banana-2",
        "display_name": "Runway Nano Banana 2",
        "kind": "image",
        "task_type": "gemini_3_1_flash_image",
        "builder_key": "gemini_image",
        "supported_modes": ["text_to_image", "image_to_image"],
        "media_roles": ["reference_image"],
        "upload_required": False,
        "feature_flags": ["gemini_3_1_flash_image"],
        "cost_feature": "gemini_3_1_flash_image",
        "default_options": {
            "model": "gemini-3.1-flash-image-preview",
            "aspect_ratio": "21:9",
            "num_images": 1,
            "image_size": "4K",
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_IMAGE,
            image_sizes=["1K", "2K", "4K"],
            prompt_max=5000,
            extra={"num_outputs": {"type": "integer", "enum": [1, 4]}},
        ),
        "limits": {"max_reference_images": 14, "max_outputs": 4},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-nano-banana-pro",
        "display_name": "Runway Nano Banana Pro",
        "kind": "image",
        "task_type": "workflow_gemini_image",
        "builder_key": "gemini_image",
        "supported_modes": ["text_to_image", "image_to_image"],
        "media_roles": ["reference_image"],
        "upload_required": False,
        "feature_flags": ["workflow_gemini_image"],
        "cost_feature": "workflow_gemini_image",
        "default_options": {
            "model": "gemini-3-pro-image-preview",
            "aspect_ratio": "16:9",
            "num_images": 1,
            "image_size": "2K",
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_IMAGE,
            image_sizes=["1K", "2K", "4K"],
            prompt_max=5000,
            extra={"num_outputs": {"type": "integer", "enum": [1, 4]}},
        ),
        "limits": {"max_reference_images": 14, "max_outputs": 4},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-gen4-image",
        "display_name": "Runway Gen-4 Image",
        "kind": "image",
        "task_type": "text_to_image",
        "builder_key": "gen4_image",
        "supported_modes": ["text_to_image", "image_to_image"],
        "media_roles": ["reference_image"],
        "upload_required": False,
        "feature_flags": ["gen4_image", "text_to_image", "ref_image_to_image"],
        "cost_feature": "gen4_image",
        "default_options": {
            "resolution": "1080p",
            "aspect_ratio": "16:9",
            "num_images": 1,
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_RUNWAY_IMAGE,
            resolutions=["720p", "1080p"],
            prompt_max=1000,
            extra={"num_outputs": {"type": "integer", "minimum": 1, "maximum": 4}},
        ),
        "limits": {"max_reference_images": 3, "max_outputs": 4},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-gen45-video",
        "display_name": "Runway Gen-4.5 Video",
        "kind": "video",
        "task_type": "gen4.5",
        "builder_key": "gen45_video",
        "supported_modes": ["text_to_video", "image_to_video", "text_to_video_audio"],
        "media_roles": ["first_frame"],
        "upload_required": False,
        "feature_flags": ["gen4.5"],
        "cost_feature": "gen4.5",
        "default_options": {
            "seconds": 5,
            "aspect_ratio": "16:9",
            "watermark": False,
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_RUNWAY_IMAGE,
            durations=list(range(2, 11)),
            prompt_max=1000,
            extra={
                "fps": {"type": "integer", "enum": [24, 25]},
                "sound": {"type": "boolean"},
            },
        ),
        "limits": {"min_duration": 2, "max_duration": 10, "max_reference_images": 1},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-kling-3-pro",
        "display_name": "Runway Kling 3.0 Pro",
        "kind": "video",
        "task_type": "kling_3_0_pro",
        "builder_key": "kling_video",
        "supported_modes": ["text_to_video", "image_to_video", "first_last_frame", "multishot"],
        "media_roles": ["reference_image", "first_frame", "last_frame"],
        "upload_required": False,
        "feature_flags": ["kling_3_0_pro"],
        "cost_feature": "kling_3_0_pro",
        "default_options": {
            "mode": "pro",
            "duration": 5,
            "aspect_ratio": "16:9",
            "resolution": "1080p",
            "cfgScale": 0.5,
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_KLING,
            resolutions=["720p", "1080p"],
            durations=list(range(3, 16)),
            prompt_max=512,
            extra={
                "sound": {"type": "boolean"},
                "multi_shot": {"type": "array", "max_items": 5},
            },
        ),
        "limits": {"min_duration": 3, "max_duration": 15, "max_multishot": 5, "min_shot_duration": 3},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-seedance-2",
        "display_name": "Runway Seedance 2.0",
        "kind": "video",
        "task_type": "seedance_2",
        "builder_key": "seedance_video",
        "supported_modes": ["text_to_video", "image_to_video", "first_last_frame", "video_reference", "audio_reference"],
        "media_roles": ["reference_image", "first_frame", "last_frame", "reference_video", "reference_audio"],
        "upload_required": False,
        "feature_flags": ["seedance_2"],
        "cost_feature": "seedance_2",
        "default_options": {
            "duration": 5,
            "aspectRatio": "16:9",
            "resolution": "720p",
            "generateAudio": False,
            "exploreMode": False,
            "creationSource": "tool-mode",
        },
        "option_schema": _schema(
            aspect_ratios=ASPECT_RATIOS_SEEDANCE,
            resolutions=["480p", "720p", "1080p"],
            durations=list(range(4, 16)),
            prompt_max=1000,
            extra={"sound": {"type": "boolean"}},
        ),
        "limits": {"max_reference_images": 9, "max_reference_videos": 3, "max_reference_audio": 3, "max_audio_seconds": 15},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-veo-3-1",
        "display_name": "Runway Veo 3.1",
        "kind": "video",
        "task_type": "veo3_1",
        "builder_key": "veo_video",
        "supported_modes": ["text_to_video", "image_to_video", "first_last_frame"],
        "media_roles": ["first_frame", "last_frame", "reference_image"],
        "upload_required": False,
        "feature_flags": ["veo3_1"],
        "cost_feature": "veo3_1",
        "default_options": {"duration": 8, "aspectRatio": "16:9", "exploreMode": False, "creationSource": "apps", "creationSourceAppId": "veo3_1"},
        "option_schema": _schema(aspect_ratios=ASPECT_RATIOS_WIDE, durations=[4, 6, 8], prompt_max=1000, extra={"sound": {"type": "boolean"}}),
        "limits": {"max_reference_images": 2},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-veo-3",
        "display_name": "Runway Veo 3",
        "kind": "video",
        "task_type": "video_with_narration",
        "builder_key": "veo_video",
        "supported_modes": ["text_to_video", "image_to_video"],
        "media_roles": ["first_frame", "reference_image"],
        "upload_required": False,
        "feature_flags": ["video_with_narration", "workflow_video_with_narration"],
        "cost_feature": "video_with_narration",
        "default_options": {"duration": 8, "aspectRatio": "16:9", "exploreMode": False, "creationSource": "apps", "creationSourceAppId": "veo3"},
        "option_schema": _schema(aspect_ratios=ASPECT_RATIOS_WIDE, durations=[4, 6, 8], prompt_max=1000, extra={"sound": {"type": "boolean"}}),
        "limits": {"max_reference_images": 1},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-text-to-speech",
        "display_name": "Runway Text to Speech",
        "kind": "audio",
        "task_type": "workflow_text_to_speech",
        "builder_key": "text_to_speech",
        "supported_modes": ["text_to_speech"],
        "media_roles": [],
        "upload_required": False,
        "feature_flags": ["workflow_text_to_speech"],
        "cost_feature": "workflow_text_to_speech",
        "default_options": {"modelId": "eleven_multilingual_v2"},
        "option_schema": _schema(prompt_max=10000, extra={"voice_id": {"type": "string"}}),
        "limits": {"cost_unit_characters": 50},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-speech-to-speech",
        "display_name": "Runway Speech to Speech",
        "kind": "audio",
        "task_type": "speech_to_speech",
        "builder_key": "speech_to_speech",
        "supported_modes": ["speech_to_speech"],
        "media_roles": ["input_audio"],
        "upload_required": True,
        "feature_flags": ["speech_to_speech"],
        "cost_feature": "speech_to_speech",
        "default_options": {},
        "option_schema": _schema(extra={"voice_id": {"type": "string"}}),
        "limits": {"max_audio_seconds": 300, "cost_unit_seconds": 3},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-sound-effects",
        "display_name": "Runway Sound Effects",
        "kind": "audio",
        "task_type": "eleven_text_to_sound_v2",
        "builder_key": "sound_effect",
        "supported_modes": ["text_to_sound"],
        "media_roles": [],
        "upload_required": False,
        "feature_flags": ["eleven_text_to_sound_v2"],
        "cost_feature": "eleven_text_to_sound_v2",
        "default_options": {"duration": 5},
        "option_schema": _schema(durations=list(range(1, 23)), prompt_max=450),
        "limits": {"max_prompt_characters": 450},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-image-upscale",
        "display_name": "Runway Image Upscale",
        "kind": "upscale",
        "task_type": "magnific_precision_upscaler_v2",
        "builder_key": "image_upscale",
        "supported_modes": ["image_upscale"],
        "media_roles": ["image_to_upscale"],
        "upload_required": True,
        "feature_flags": ["magnific_precision_upscaler_v2"],
        "cost_feature": "magnific_precision_upscaler_v2",
        "default_options": {"scaleFactor": 2, "flavor": "sublime", "sharpen": 0, "smartGrain": 0, "ultraDetail": 0, "creationSource": "tool-mode"},
        "option_schema": _schema(prompt_max=4000, extra={"scale": {"type": "integer", "enum": [2, 4, 8, 16]}}),
        "limits": {"min_width": 300, "min_height": 300, "scale_factors": [2, 4, 8, 16]},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-video-upscale",
        "display_name": "Runway Video Upscale",
        "kind": "upscale",
        "task_type": "media_upscale",
        "builder_key": "video_upscale",
        "supported_modes": ["video_upscale"],
        "media_roles": ["video_to_upscale"],
        "upload_required": True,
        "feature_flags": ["media_upscale"],
        "cost_feature": "media_upscale",
        "default_options": {"scaleFactor": 2, "creationSource": "tool-mode"},
        "option_schema": _schema(extra={"scale": {"type": "integer", "enum": [2, 4]}}),
        "limits": {"max_video_seconds": 40},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-talking-avatar",
        "display_name": "Runway Talking Avatar",
        "kind": "video",
        "task_type": "workflow_talking_avatar",
        "builder_key": "talking_avatar",
        "supported_modes": ["character_text_to_video", "character_audio_to_video"],
        "media_roles": ["character_image", "input_audio"],
        "upload_required": True,
        "feature_flags": ["workflow_talking_avatar"],
        "cost_feature": "workflow_talking_avatar",
        "default_options": {"creationSource": "tool-mode"},
        "option_schema": _schema(prompt_max=10000, extra={"voice_id": {"type": "string"}}),
        "limits": {},
        "default_enabled": True,
    },
    {
        "public_model_id": "runway-sora",
        "display_name": "Runway Sora",
        "kind": "video",
        "task_type": "sora",
        "builder_key": "unsupported",
        "supported_modes": ["text_to_video", "image_to_video"],
        "media_roles": ["first_frame", "reference_image"],
        "upload_required": False,
        "feature_flags": ["sora"],
        "cost_feature": "sora",
        "default_options": {},
        "option_schema": _schema(aspect_ratios=ASPECT_RATIOS_WIDE),
        "limits": {},
        "default_enabled": False,
        "disabled_reason": "Captured as visible model, but exact task builder was not confirmed.",
    },
    {
        "public_model_id": "runway-wan",
        "display_name": "Runway WAN",
        "kind": "video",
        "task_type": "wan",
        "builder_key": "unsupported",
        "supported_modes": ["text_to_video", "image_to_video"],
        "media_roles": ["first_frame", "reference_image"],
        "upload_required": False,
        "feature_flags": ["wan"],
        "cost_feature": "wan",
        "default_options": {},
        "option_schema": _schema(aspect_ratios=ASPECT_RATIOS_WIDE),
        "limits": {},
        "default_enabled": False,
        "disabled_reason": "Captured as visible model, but exact task builder was not confirmed.",
    },
    {
        "public_model_id": "runway-grok-video",
        "display_name": "Runway Grok Video",
        "kind": "video",
        "task_type": "grok_video",
        "builder_key": "unsupported",
        "supported_modes": ["text_to_video", "image_to_video"],
        "media_roles": ["first_frame", "reference_image"],
        "upload_required": False,
        "feature_flags": ["grok_video"],
        "cost_feature": "grok_video",
        "default_options": {},
        "option_schema": _schema(aspect_ratios=ASPECT_RATIOS_WIDE),
        "limits": {},
        "default_enabled": False,
        "disabled_reason": "Captured as visible model, but exact task builder was not confirmed.",
    },
]


def runway_manifest_by_id() -> Dict[str, Dict[str, Any]]:
    return {str(item["public_model_id"]): deepcopy(item) for item in RUNWAY_MODEL_MANIFEST}


def runway_manifest_entry(public_model_id: str) -> Optional[Dict[str, Any]]:
    return runway_manifest_by_id().get((public_model_id or "").strip())
